/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#121409',
        surface: '#121409',
        'surface-dim': '#121409',
        'surface-bright': '#383a2d',
        'surface-container-lowest': '#0d0f05',
        'surface-container-low': '#1a1d11',
        'surface-container': '#1e2115',
        'surface-container-high': '#292b1e',
        'surface-container-highest': '#343629',
        'surface-variant': '#343629',
        'surface-tint': '#b0d500',
        'on-surface': '#e3e4d0',
        'on-surface-variant': '#c5c9ae',
        'on-background': '#e3e4d0',
        'inverse-surface': '#e3e4d0',
        'inverse-on-surface': '#2f3224',
        'inverse-primary': '#536600',
        outline: '#8f937a',
        'outline-variant': '#454934',
        primary: '#ffffff',
        'on-primary': '#2a3500',
        'primary-container': '#cbf22b',
        'on-primary-container': '#586c00',
        'primary-fixed': '#cbf22b',
        'primary-fixed-dim': '#b0d500',
        'on-primary-fixed': '#171e00',
        'on-primary-fixed-variant': '#3e4c00',
        secondary: '#c9c6c0',
        'on-secondary': '#31302d',
        'secondary-container': '#4a4945',
        'on-secondary-container': '#bbb8b2',
        tertiary: '#ffffff',
        'on-tertiary': '#332e3d',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        signal: '#FF4D2E',
      },
      borderRadius: {
        DEFAULT: '0px',
        none: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        '3xl': '0px',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        gutter: '16px',
        'margin-mobile': '20px',
        'section-gap': '80px',
        unit: '4px',
      },
      fontFamily: {
        'display-xl': ['"Bebas Neue"', 'sans-serif'],
        'headline-lg': ['"Bebas Neue"', 'sans-serif'],
        'headline-lg-mobile': ['"Bebas Neue"', 'sans-serif'],
        'headline-md': ['"Bebas Neue"', 'sans-serif'],
        'data-point': ['"Bebas Neue"', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'label-caps': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['120px', { lineHeight: '100px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['64px', { lineHeight: '60px', letterSpacing: '0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['48px', { lineHeight: '44px', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '32px', letterSpacing: '0.04em', fontWeight: '700' }],
        'data-point': ['40px', { lineHeight: '40px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
      },
      animation: {
        'fade-in': 'fadeIn 0.4s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
